Repository kubernetes/kube-openapi, pull requests merged in 2018-10, with the labels that each got.

#108 remove unneeded parameter
  pkg/generators/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#105 Allow using top-level Responses Definitions field in openapi v2
  pkg/builder/openapi.go
  pkg/common/common.go
  test/integration/builder/main.go
  test/integration/testdata/golden.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#110 Convert OpenAPI to structured schema
  cmd/openapi2smd/openapi2smd.go
  pkg/schemaconv/smd.go
  pkg/schemaconv/smd_test.go
  pkg/schemaconv/testdata/new-schema.yaml
  pkg/schemaconv/testdata/swagger.json
  pkg/util/proto/document.go
  pkg/util/proto/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#111 Fix api linter
  pkg/generators/api_linter.go
  pkg/generators/openapi.go
  test/integration/builder/main.go
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#106 Add linting test for omitempty
  pkg/generators/api_linter.go
  pkg/generators/rules/omitempty_match_case.go
  pkg/generators/rules/omitempty_match_case_test.go
  test/integration/testdata/golden.json
  test/integration/testdata/golden.report
  test/integration/testdata/listtype/map-list.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#107 Add roycaihw to reviewers and update integration test README
  OWNERS
  pkg/generators/rules/OWNERS
  test/integration/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#113 fix path mangling
  pkg/generators/api_linter.go
  pkg/generators/config.go
  test/integration/pkg/generated/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/M
