Repository kubernetes/kube-openapi, pull requests merged in 2018-07, with the labels that each got.

#90 Copy apimachinery sets util to avoid import cycle
  Godeps/Godeps.json
  pkg/generators/rules/names_match.go
  pkg/util/sets/empty.go
  pkg/util/sets/string.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#93 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 Correction in README.md
  test/integration/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS
