Repository kubernetes/kube-openapi, pull requests merged in 2018-04, with the labels that each got.

#43 Refactor to make it easier to add extension tags
  pkg/generators/openapi.go
Labels: cncf-cla: yes, lgtm, size/M

#45 Sort map keys for deterministic testing
  pkg/generators/openapi.go
Labels: cncf-cla: yes, lgtm, size/S

#44 Some typo fix
  pkg/aggregator/aggregator.go
  pkg/builder/openapi.go
  pkg/common/common.go
  pkg/handler/handler.go
Labels: cncf-cla: yes, size/S

#49 Added unit tests to util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, size/M

#47 Use k8s GCR vanity URL
  pkg/util/proto/testing/swagger.json
Labels: cncf-cla: yes, size/XS

#48 Add listAttribute extension
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, size/S

#50 Multi-value extensions
  pkg/generators/extension.go
  pkg/generators/extension_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/L

#55 More descriptive error messages for extensions
  pkg/generators/extension.go
  pkg/generators/extension_test.go
  pkg/generators/openapi.go
Labels: cncf-cla: yes, lgtm, size/L

#57 extension fields renaming
  pkg/generators/extension.go
  pkg/generators/extension_test.go
  pkg/generators/openapi.go
Labels: cncf-cla: yes, lgtm, size/M

#56 Start putting up documentation for the Go IDL
  pkg/idl/doc.go
  pkg/idl/listtype_test.go
Labels: cncf-cla: yes, lgtm, size/L

#58 idl-doc: Further improvements
  pkg/idl/doc.go
  pkg/idl/listtype_test.go
  pkg/idl/maptype_test.go
  pkg/idl/structtype_test.go
Labels: cncf-cla: yes, lgtm, size/L
