Repository kubernetes/kube-openapi, pull requests merged in 2018-05, with the labels that each got.

#64 Properly initialize spec.Definitions when merging specs
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
Labels: cncf-cla: yes, lgtm, size/L

#67 Allow specs to have empty Paths in aggregation
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
Labels: cncf-cla: yes, lgtm, size/L

#68 Prepare cherry-picking #64 and #67 to release-1.10
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
Labels: cncf-cla: yes, size/L

#69 Prepare cherry-picking #64 and #67 to release-1.9
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
Labels: cncf-cla: yes, size/L

#71 cherry-picking #64 and #67 to release-1.8
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
Labels: lgtm, size/L

#72 Additional approvers and reviewers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#74 Allow openapi definitions to be built for a single resource
  pkg/builder/openapi.go
  pkg/builder/openapi_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#59 Remove unnecessarily stored spec
  pkg/handler/handler.go
Labels: cncf-cla: yes, size/XS

#65 Typo fix in swagger.json: mulitple->multiple
  pkg/util/proto/testing/swagger.json
Labels: cncf-cla: yes, lgtm, size/XS

#63 Typo fix: compatability->compatibility
  pkg/util/proto/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#77 proto: Add validation tests
  pkg/util/proto/validation/validation_suite_test.go
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#79 proto: Move test swagger files to testdata
  pkg/util/proto/openapi_test.go
  pkg/util/proto/testdata/swagger.json
  pkg/util/proto/testdata/swagger_next.json
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#80 proto: Add "Empty" fake
  pkg/util/proto/testing/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
