Repository kubernetes/kube-openapi, pull requests merged in 2018-09, with the labels that each got.

#102 Move getCanonicalTypeName to util package and export it
  pkg/builder/openapi.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#100 pkg/generators README markdown updates
  pkg/generators/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#99 Typo fix in pkg/generators/api_linter.go
  pkg/generators/api_linter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#94 Skip merge source spec with empty paths
  pkg/aggregator/aggregator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#88 fix some formt error using gofmt
  pkg/aggregator/aggregator.go
  pkg/builder/openapi_test.go
  pkg/generators/extension.go
Labels: approved, cncf-cla: yes, lgtm, size/S
