Repository kubernetes/kube-openapi, pull requests merged in 2019-01, with the labels that each got.

#126 Switch location for goautoneg vendored code
  Godeps/Godeps.json
  pkg/handler/handler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 travis: fix hg SSL issue by using Ubuntu LTS 16.04 Xenial
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 Add type: object to all generated struct objects
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/testdata/golden.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#124 aggregator: optimize 40x speed, 1/8 mem, 1/27 allocs
  Godeps/Godeps.json
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
  pkg/aggregator/mutating_walker.go
  pkg/aggregator/mutating_walker_test.go
  pkg/aggregator/walker.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  test/integration/testdata/aggregator/openapi-0.json
  test/integration/testdata/aggregator/openapi-1.json
  test/integration/testdata/aggregator/openapi-2.json
  test/integration/testdata/aggregator/openapi.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL
