Repository kubernetes/kube-openapi, pull requests merged in 2019-02, with the labels that each got.

#136 aggregator: fix and extend mutating walker tests
  pkg/aggregator/mutating_walker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#133 schemaconv: Make RawExtension into an untyped atomic scalar
  pkg/schemaconv/smd.go
  pkg/schemaconv/testdata/new-schema.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯

#138 handler: fix ToProtoBinary and add tests
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#132 Allow model to seed name without go type
  pkg/util/util.go
  pkg/util/util_test.go
  test/integration/README.md
  test/integration/builder/main.go
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/golden.json
  test/integration/testdata/golden.report
Labels: approved, cncf-cla: yes, lgtm, size/L

#140 generator: make output roundtrippable
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#145 handler: use stdlib compatible json-iter encoder for stable map order
  pkg/handler/handler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#146 cleanup: remove deprecated service registration
  pkg/handler/handler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 Add sttts as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#148 cmd/openapi-gen: be silent on success
  cmd/openapi-gen/openapi-gen.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#149 handler: convert int types correctly like yaml2 does and gnostic expects
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
