Repository kubernetes/kube-openapi, pull requests merged in 2019-05, with the labels that each got.

#160 Remove constraint on discriminator type
  pkg/generators/union.go
  pkg/schemaconv/smd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#161 Remove check on discriminator
  pkg/generators/union.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Add api lint rule for missing list type
  pkg/generators/api_linter.go
  pkg/generators/rules/idl_tag.go
  pkg/generators/rules/idl_tag_test.go
  test/integration/README.md
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/golden.report
  test/integration/testdata/listtype/untyped.go
Labels: approved, cncf-cla: yes, lgtm, size/L, wg/apply

#165 Update structured-merge-diff version
  go.mod
  go.sum
  pkg/schemaconv/smd.go
  pkg/schemaconv/testdata/new-schema.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL
