Repository kubernetes/kube-openapi, pull requests merged in 2019-07, with the labels that each got.

#150 aggregator: merge x-kubernetes-group-version-kind slices
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#168 Update googleapis/gnostic
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 Support x-kubernetes-v2-spec extension
  pkg/builder/openapi.go
  pkg/builder/openapi_test.go
  pkg/common/common.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/builder/main.go
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/custom/v2.go
  test/integration/testdata/custom/v3.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v2.report
Labels: approved, cncf-cla: yes, lgtm, size/XL
