Repository kubernetes/kube-openapi, pull requests merged in 2019-04, with the labels that each got.

#143 Add analysis of pkg/util/proto/validator
  pkg/util/proto/document.go
  pkg/util/proto/validation/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#154 Create go-modules to replace Godeps
  .travis.yml
  Godeps/Godeps.json
  Godeps/Readme
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#155 Update structured-merge-diff version
  go.mod
  go.sum
  pkg/schemaconv/smd.go
  pkg/schemaconv/testdata/new-schema.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#157 Replace seans with apelisse from approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#152 Add parsing of openapi oneof/union semantic into smd
  go.mod
  go.sum
  pkg/schemaconv/smd.go
  pkg/schemaconv/testdata/new-schema.yaml
  pkg/schemaconv/testdata/swagger.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#156 Parse union tags in IDL, generate proper openapi
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  pkg/generators/union.go
  test/integration/README.md
  test/integration/builder/main.go
  test/integration/integration_suite_test.go
  test/integration/testdata/golden.json
  test/integration/testdata/uniontype/union.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#159 Rename `fields-discriminated` to `fields-to-discriminateBy`
  pkg/generators/openapi_test.go
  pkg/generators/union.go
  pkg/schemaconv/smd.go
  pkg/schemaconv/testdata/swagger.json
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/golden.json
  test/integration/testdata/uniontype/union.go
Labels: approved, cncf-cla: yes, lgtm, size/L
