Repository kubernetes/kube-openapi, pull requests merged in 2020-11, with the labels that each got.

#212 Converts OpenAPI defaults to structured-merge-diff schema
  go.mod
  go.sum
  pkg/schemaconv/smd.go
  pkg/schemaconv/smd_test.go
  pkg/schemaconv/testdata/defaults.json
  pkg/schemaconv/testdata/defaults.yaml
  pkg/util/proto/document.go
  pkg/util/proto/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#213 Fix unexpected error values
  pkg/validation/errors/schema.go
  pkg/validation/errors/schema_test.go
  pkg/validation/validate/validator.go
  pkg/validation/validate/values.go
  pkg/validation/validate/values_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#214 validation: add OWNERS
  pkg/validation/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 Generate OpenAPI default field from +default comment marker
  pkg/builder/openapi.go
  pkg/common/common.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  pkg/handler/handler.go
  pkg/handler/internal/default_pruning.go
  pkg/handler/internal/default_pruning_test.go
  test/integration/README.md
  test/integration/builder/main.go
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/defaults/default.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v2.report
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#215 Revert "Do not publish defaults in the OpenAPI"
  pkg/handler/handler.go
  pkg/handler/internal/default_pruning.go
  pkg/handler/internal/default_pruning_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#216 PruneDefaults from OpenAPI definitions
  pkg/handler/default_pruning.go
  pkg/handler/default_pruning_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#217 Make PruneDefaultsSchema public
  pkg/handler/default_pruning.go
Labels: approved, cncf-cla: yes, lgtm, size/M
