Repository kubernetes/kube-openapi, pull requests merged in 2020-08, with the labels that each got.

#200 kube-openapi release-1.19 uses smd v4
  go.mod
  go.sum
  pkg/schemaconv/smd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#202 Add x-kubernetes-map-type: atomic support
  pkg/schemaconv/smd.go
  pkg/schemaconv/smd_test.go
  pkg/schemaconv/testdata/atomic-types.json
  pkg/schemaconv/testdata/atomic-types.yaml
  pkg/schemaconv/testdata/new-schema.yaml
  pkg/schemaconv/testdata/swagger.json
  test/integration/README.md
  test/integration/builder/main.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v2.report
  test/integration/testdata/structtype/atomic-struct.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#204 Fix openAPI x-kubernetes-map-type enum to be "granular"
  pkg/schemaconv/smd.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/api-machinery, size/XS

#208 kube-openapi release-1.19 uses smd v4
  go.mod
  go.sum
  pkg/schemaconv/smd.go
  pkg/schemaconv/testdata/atomic-types.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
