Repository kubernetes/kube-openapi, pull requests merged in 2020-04, with the labels that each got.

#189 update gnostic dependency
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/handler/handler.go
  pkg/util/proto/document.go
  pkg/util/proto/testing/openapi.go
  test/integration/pkg/generated/openapi_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#190 Remove part about discarding `openapi.go`
  test/integration/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 Fix client-side validation of integer literals for number fields
  pkg/util/proto/testdata/swagger.json
  pkg/util/proto/validation/types.go
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#194 Fix client-side validation of integer literals for number fields
  pkg/util/proto/testdata/swagger.json
  pkg/util/proto/validation/types.go
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#193 Fix client-side validation of integer literals for number fields
  pkg/util/proto/testdata/swagger.json
  pkg/util/proto/validation/types.go
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#195 Fix client-side validation of integer literals for number fields
  pkg/util/proto/testdata/swagger.json
  pkg/util/proto/validation/types.go
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#196 Switch to newer gengo and klog v2
  cmd/openapi-gen/openapi-gen.go
  go.mod
  go.sum
  pkg/generators/api_linter.go
  pkg/generators/config.go
  pkg/generators/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#192 k8s.io/kube-openapi:upgrade k8s.io/klog to v2
  cmd/openapi-gen/openapi-gen.go
  go.mod
  go.sum
  pkg/generators/api_linter.go
  pkg/generators/config.go
  pkg/generators/openapi.go
Labels: cncf-cla: yes, size/S

#197 Add myself to SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS
