Repository kubernetes/kube-openapi, pull requests merged in 2021-02, with the labels that each got.

#226 Added github-action CI
  .github/workflows/ci_pipeline.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#229 Drop ghodss/yaml and switch to sigs.k8s.io/yaml
  go.mod
  go.sum
  pkg/util/proto/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#228 Remove inactive members from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
