Repository kubernetes/kube-openapi, pull requests merged in 2021-03, with the labels that each got.

#231 go mod tidy
  go.sum
Labels: cncf-cla: yes, size/XS

#230 Remove incorrect zero value check
  pkg/validation/validate/type.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#232 fix for hardcoded path needed to pass tests in github-ci
  .github/workflows/ci.yml
  .github/workflows/ci_pipeline.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#220 Update gnostic to v0.5.1
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/aggregator/aggregator_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/util/proto/testing/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/M
