Repository kubernetes/kube-openapi, pull requests merged in 2021-11, with the labels that each got.

#251 Lazy marshaling for OpenAPI v2 spec
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#261 Revert cel related changes
  go.mod
  go.sum
  pkg/generators/extension.go
  pkg/util/cel/compilation.go
  pkg/util/cel/compilation_test.go
  pkg/validation/errors/schema.go
  pkg/validation/spec/info.go
  pkg/validation/validate/cel_expression_validator.go
  pkg/validation/validate/cel_expression_validator_test.go
  pkg/validation/validate/schema.go
  pkg/validation/validate/schema_option.go
  pkg/validation/validate/schema_test.go
  third_party/forked/celopenapi/model/README.md
  third_party/forked/celopenapi/model/env.go
  third_party/forked/celopenapi/model/env_test.go
  third_party/forked/celopenapi/model/registry.go
  third_party/forked/celopenapi/model/schemas.go
  third_party/forked/celopenapi/model/schemas_test.go
  third_party/forked/celopenapi/model/source.go
  third_party/forked/celopenapi/model/types.go
  third_party/forked/celopenapi/model/types_test.go
  third_party/forked/celopenapi/model/value.go
  third_party/forked/celopenapi/model/value_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#263 Recursive mutating schema walker.
  pkg/aggregator/aggregator.go
  pkg/schemamutation/walker.go
  pkg/schemamutation/walker_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#244 CI go version mapping upgrade
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#266 cherry-picking #220 and #251 to release-1.20
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/aggregator/aggregator_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/util/proto/testing/openapi.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#265 cherry-picking #220 and #251 to release-1.21
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/aggregator/aggregator_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/util/proto/testing/openapi.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#264 cherry-picking #251 to release-1.22
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#267 revert #265 and cherry-pick only #251
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/aggregator/aggregator_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/util/proto/testing/openapi.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#268 revert #266 and cherry-pick only #251
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/aggregator/aggregator_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/util/proto/testing/openapi.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#269 OpenAPI Enums: Format update
  pkg/generators/enum.go
  pkg/generators/openapi_test.go
  test/integration/pkg/generated/openapi_generated.go
Labels: cncf-cla: yes, lgtm, size/S, approved
