Repository kubernetes/kube-openapi, pull requests merged in 2022-11, with the labels that each got.

#322 Consistently find enum values from separate packages in openapi-gen.
  pkg/generators/enum.go
  pkg/generators/enum_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#327 support pointer of enum types.
  pkg/generators/enum.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#328 cleanup code in builder3 test
  test/integration/builder3/main.go
Labels: cncf-cla: yes, lgtm, size/S, approved, kind/cleanup

#330 Add apelisse as approver to pkg/validation
  pkg/validation/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved
