Repository kubernetes/kube-openapi, pull requests merged in 2022-01, with the labels that each got.

#273 Set path for specific validators when set on parent SchemaValidator and use JSONPath syntax
  pkg/validation/validate/object_validator.go
  pkg/validation/validate/schema.go
  pkg/validation/validate/schema_props.go
  pkg/validation/validate/slice_validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#252 Decouple REST Framework
  pkg/builder/openapi.go
  pkg/builder/util.go
  pkg/builder3/openapi.go
  pkg/builder3/util.go
  pkg/common/common.go
  pkg/common/interfaces.go
  pkg/common/restfuladapter/adapter.go
  pkg/common/restfuladapter/param_adapter.go
  pkg/common/restfuladapter/response_error_adapter.go
  pkg/common/restfuladapter/route_adapter.go
  pkg/common/restfuladapter/webservice_adapter.go
  pkg/handler/handler.go
  test/integration/README.md
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/dummytype/alpha.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v2.report
  test/integration/testdata/golden.v3.json
  test/integration/testutil/testutil.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#272 Add lazy marshaling for OpenAPIv3
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler3/handler.go
  pkg/internal/handler/handler_cache.go
  pkg/internal/handler/handler_cache_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#276 Fix typo in OWNERS file
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved
