Repository kubernetes/kube-openapi, pull requests merged in 2022-06, with the labels that each got.

#303 Move to newer version (v3) of github.com/emicklei/go-restful
  go.mod
  go.sum
  pkg/builder/openapi.go
  pkg/builder/openapi_test.go
  pkg/builder3/openapi.go
  pkg/builder3/openapi_test.go
  pkg/common/common.go
  pkg/common/restfuladapter/adapter.go
  pkg/common/restfuladapter/param_adapter.go
  pkg/common/restfuladapter/response_error_adapter.go
  pkg/common/restfuladapter/route_adapter.go
  pkg/common/restfuladapter/webservice_adapter.go
  pkg/handler/handler.go
  test/integration/testutil/testutil.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#304 Switch to released version of v3.8.0 - github.com/emicklei/go-restful/v3
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved

#306 Go 1.18
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved

#302 upgrade ginkgo to ginkgo/v2
  go.mod
  go.sum
  pkg/util/proto/openapi_suite_test.go
  pkg/util/proto/openapi_test.go
  pkg/util/proto/validation/validation_suite_test.go
  pkg/util/proto/validation/validation_test.go
  test/integration/integration_suite_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved
