Repository kubernetes/kube-openapi, pull requests merged in 2022-03, with the labels that each got.

#282 add vendor extensions to marshal openapi v2 spec.Header
  pkg/validation/spec/header.go
  pkg/validation/spec/header_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#285 Change references of googleapis/gnostic -> google/gnostic
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/handler/handler.go
  pkg/handler3/handler.go
  pkg/util/proto/document.go
  pkg/util/proto/testing/openapi.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#288 Update gnostic to drop jsonschema dependency
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#284 Cache busting
  pkg/handler/handler.go
  pkg/handler3/handler.go
  pkg/handler3/handler_test.go
  pkg/internal/handler/handler_cache.go
  pkg/internal/handler/handler_cache_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#291 Add unit tests for builder3
  pkg/builder3/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#293 Implement proto.Models for OpenAPI v3
  go.mod
  pkg/util/proto/document_v3.go
  pkg/util/proto/openapi_test.go
  pkg/util/proto/testdata/openapi_v3_0_0/apiextensions.k8s.io/v1.json
  pkg/util/proto/testdata/openapi_v3_0_0/apps/v1.json
  pkg/util/proto/testdata/openapi_v3_0_0/batch/v1.json
  pkg/util/proto/testdata/openapi_v3_0_0/batch/v1beta1.json
  pkg/util/proto/testdata/openapi_v3_0_0/v1.json
  pkg/util/proto/testing/openapi_v3.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#289 add support for custom v3 oneOf types
  pkg/common/common.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/custom/v3.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#290 do not include v2 schema when serving v3
  pkg/builder3/openapi.go
  pkg/builder3/openapi_test.go
  test/integration/testdata/golden.v3.json
Labels: cncf-cla: yes, lgtm, size/S, approved

#295 Fix json encoding for OpenAPI v3 Discovery
  pkg/handler3/handler.go
  pkg/handler3/handler_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#297 Return valid field in Validation struct
  pkg/validation/errors/headers.go
  pkg/validation/errors/schema.go
  pkg/validation/errors/schema_test.go
  pkg/validation/validate/object_validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#298 Wrap Refs with AllOf
  pkg/builder3/openapi.go
  pkg/builder3/openapi_test.go
  test/integration/testdata/golden.v3.json
Labels: cncf-cla: yes, lgtm, size/L, approved

#299 Optimize GetOpenAPIDefinitions to avoid generating the map for all definitions on every BuildOpenAPISpec invocation
  pkg/builder3/openapi.go
  pkg/common/common.go
Labels: cncf-cla: yes, lgtm, size/S, approved
