Repository kubernetes/kube-openapi, pull requests merged in 2023-09, with the labels that each got.

#419 Adds support for Symbol references in defaults
  go.mod
  go.sum
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/go.mod
  test/integration/go.sum
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/defaults/default.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v3.json
Labels: cncf-cla: yes, lgtm, size/L, approved

#405 cache: making it more Go idiomatic
  pkg/cached/cache.go
  pkg/cached/cache_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler3/handler.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#416 Implement experimental marshaler for OpenAPI V3
  pkg/internal/flags.go
  pkg/spec3/benchmark_serialization_test.go
  pkg/spec3/encoding.go
  pkg/spec3/example.go
  pkg/spec3/external_documentation.go
  pkg/spec3/fuzz.go
  pkg/spec3/header.go
  pkg/spec3/media_type.go
  pkg/spec3/operation.go
  pkg/spec3/parameter.go
  pkg/spec3/path.go
  pkg/spec3/request_body.go
  pkg/spec3/response.go
  pkg/spec3/security_scheme.go
  pkg/spec3/server.go
  pkg/spec3/spec.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#430 Do not import github.com/google/go-cmp/cmp outside tests.
  pkg/validation/spec/fuzz_test.go
  test/integration/go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#432 Add security requirement to root OpenAPI V3
  pkg/spec3/fuzz.go
  pkg/spec3/spec.go
Labels: cncf-cla: yes, lgtm, size/S, approved
