Repository kubernetes/kube-openapi, pull requests merged in 2023-03, with the labels that each got.

#377 spec: Fix missing field in v2 serialization
  pkg/spec3/fuzz.go
  pkg/util/jsontesting/json_roundtrip.go
  pkg/validation/spec/schema.go
  pkg/validation/spec/schema_test.go
  pkg/validation/spec/swagger.go
  pkg/validation/spec/swagger_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#371 Use smarter cache
  pkg/cached/cache.go
  pkg/cached/cache_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler3/handler.go
  pkg/handler3/handler_test.go
  pkg/internal/handler/handler_cache.go
  pkg/internal/handler/handler_cache_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#380 Bump go version to 1.19
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved
