Repository kubernetes/kube-openapi, pull requests merged in 2023-05, with the labels that each got.

#387 Fix cache data race
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#388 Update CI to detect races
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#391 cached: Make atomicity constraints more vocal
  pkg/cached/cache.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#390 Drop unused mapstructure functionality
  go.mod
  go.sum
  pkg/validation/strfmt/format.go
  pkg/validation/strfmt/format_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#392 Remove empty error returned from registering OpenAPI
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#398 cached: Do not sort ListMerger test outputs
  pkg/cached/cache_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#399 cached: Add test to show that diamond is thread-safe
  pkg/cached/cache_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#402 Use gnostic-models over gnostic
  cmd/openapi2smd/openapi2smd.go
  go.mod
  go.sum
  pkg/handler/handler.go
  pkg/handler3/handler.go
  pkg/schemaconv/openapi_test.go
  pkg/util/proto/document.go
  pkg/util/proto/document_v3.go
  pkg/util/proto/openapi_test.go
  pkg/util/proto/testing/openapi.go
  pkg/util/proto/testing/openapi_v3.go
  pkg/validation/spec/gnostic.go
  pkg/validation/spec/gnostic_test.go
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved
