Repository kubernetes/kube-openapi, pull requests merged in 2023-01, with the labels that each got.

#347 Fix wrong extension name in parse schema
  pkg/util/proto/document_v3.go
  pkg/util/proto/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#349 Protect against divide-by-zero panic with multipleOf
  pkg/validation/validate/values.go
  pkg/validation/validate/values_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#346 Fix integration tests
  .github/workflows/ci.yml
  test/integration/go.mod
  test/integration/go.sum
  test/integration/import.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#348 Fix GO-2022-0493 and GO-2022-1059
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#353 Tidy integration go.mod
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved

#352 Revert content type change
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#351 Improve format of generated enum lines
  pkg/generators/enum.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#350 Remove deprecated ioutil
  cmd/openapi2smd/openapi2smd.go
  pkg/aggregator/aggregator_test.go
  pkg/generators/api_linter.go
  pkg/handler/handler_test.go
  pkg/handler3/handler_test.go
  pkg/openapiconv/convert_test.go
  pkg/schemaconv/smd_test.go
  pkg/util/proto/testing/openapi.go
  pkg/util/proto/testing/openapi_v3.go
  pkg/validation/validate/debug_test.go
  pkg/validation/validate/jsonschema_test.go
  test/integration/builder/main.go
  test/integration/builder3/main.go
  test/integration/integration_suite_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#344 Bump github.com/go-openapi/jsonreference
  go.mod
  go.sum
  pkg/validation/spec/gnostic_test.go
  pkg/validation/spec/swagger_test.go
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#339 Add direct conversion from spec.Schema to SMD schema.Schema
  pkg/builder3/openapi.go
  pkg/schemaconv/openapi.go
  pkg/schemaconv/openapi_test.go
  pkg/schemaconv/proto_models.go
  pkg/schemaconv/smd.go
  pkg/schemaconv/smd_test.go
  pkg/schemaconv/testdata/crds/openapiv2/accesscontextmanager_v1beta1_accesscontextmanagerserviceperimeter.json
  pkg/schemaconv/testdata/crds/openapiv2/container_v1beta1_containercluster.json
  pkg/schemaconv/testdata/crds/openapiv2/dataproc_v1beta1_dataprocworkflowtemplate.json
  pkg/schemaconv/testdata/crds/openapiv2/dlp_v1beta1_dlpdeidentifytemplate.json
  pkg/schemaconv/testdata/crds/openapiv2/monitoring_v1beta1_monitoringalertpolicy.json
  pkg/schemaconv/testdata/crds/openapiv2/monitoring_v1beta1_monitoringdashboard.json
  pkg/schemaconv/testdata/crds/openapiv2/privateca_v1beta1_privatecacertificate.json
  pkg/schemaconv/testdata/crds/openapiv2/privateca_v1beta1_privatecacertificateauthority.json
  pkg/schemaconv/testdata/crds/openapiv2/storagetransfer_v1beta1_storagetransferjob.json
  pkg/schemaconv/testdata/crds/openapiv2/vpcaccess_v1beta1_vpcaccessconnector.json
  pkg/schemaconv/testdata/crds/openapiv3/accesscontextmanager_v1beta1_accesscontextmanagerserviceperimeter.json
  pkg/schemaconv/testdata/crds/openapiv3/container_v1beta1_containercluster.json
  pkg/schemaconv/testdata/crds/openapiv3/dataproc_v1beta1_dataprocworkflowtemplate.json
  pkg/schemaconv/testdata/crds/openapiv3/dlp_v1beta1_dlpdeidentifytemplate.json
  pkg/schemaconv/testdata/crds/openapiv3/monitoring_v1beta1_monitoringalertpolicy.json
  pkg/schemaconv/testdata/crds/openapiv3/monitoring_v1beta1_monitoringdashboard.json
  pkg/schemaconv/testdata/crds/openapiv3/privateca_v1beta1_privatecacertificate.json
  pkg/schemaconv/testdata/crds/openapiv3/privateca_v1beta1_privatecacertificateauthority.json
  pkg/schemaconv/testdata/crds/openapiv3/storagetransfer_v1beta1_storagetransferjob.json
  pkg/schemaconv/testdata/crds/openapiv3/vpcaccess_v1beta1_vpcaccessconnector.json
  pkg/schemaconv/testdata/new-schema.yaml
  pkg/schemaconv/testdata/preserve-unknown.yaml
  pkg/schemaconv/testdata/swagger.json
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#362 Fix incorrect types OpenAPI V3
  pkg/spec3/encoding.go
  pkg/spec3/operation.go
  pkg/spec3/security_requirement.go
  pkg/spec3/security_requirement_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#367 remove use of embed so CRDs aren't pulled into vendor
  pkg/schemaconv/openapi.go
  pkg/schemaconv/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#361 Add json Unmarshal benchmark for OpenAPI V3 (No unmarshal changes)
  pkg/internal/flags.go
  pkg/spec3/benchmark_serialization_test.go
  pkg/spec3/testdata/appsv1spec.json
  pkg/spec3/testdata/authorizationv1spec.json
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#355 Cleanup CI config
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/S, approved

#363 Move sanitize and fromMap to internal package
  pkg/internal/serialization.go
  pkg/internal/serialization_test.go
  pkg/validation/spec/header.go
  pkg/validation/spec/info.go
  pkg/validation/spec/items.go
  pkg/validation/spec/operation.go
  pkg/validation/spec/parameter.go
  pkg/validation/spec/path_item.go
  pkg/validation/spec/paths.go
  pkg/validation/spec/ref.go
  pkg/validation/spec/response.go
  pkg/validation/spec/responses.go
  pkg/validation/spec/security_scheme.go
  pkg/validation/spec/swagger.go
  pkg/validation/spec/tag.go
Labels: cncf-cla: yes, lgtm, size/L, approved
