Repository kubernetes/kube-openapi, pull requests merged in 2023-07, with the labels that each got.

#411 Deduplicate parameters via references
  pkg/aggregator/aggregator.go
  pkg/aggregator/aggregator_test.go
  pkg/aggregator/walker.go
  pkg/builder/openapi.go
  pkg/builder/openapi_test.go
  pkg/builder/parameters.go
  pkg/builder/parameters_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#406 validate: Expose hooks to inject custom behavior during traversal
  pkg/validation/validate/object_validator.go
  pkg/validation/validate/object_validator_test.go
  pkg/validation/validate/schema.go
  pkg/validation/validate/schema_option.go
  pkg/validation/validate/slice_validator.go
  pkg/validation/validate/validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#412 validate: dont short circuit validator on MinProperties/MaxProperties error
  pkg/validation/validate/object_validator.go
  pkg/validation/validate/object_validator_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#414 fixup broken test
  pkg/validation/validate/object_validator_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#415 builder/parameters: switch to fnv and exclude fieldValidation query parameter
  pkg/builder/openapi_test.go
  pkg/builder/parameters.go
  pkg/builder/parameters_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved
