Repository kubernetes/kube-openapi, pull requests merged in 2023-06, with the labels that each got.

#403 Thread safe cached
  pkg/cached/cache.go
  pkg/cached/cache_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#385 Make sure updating spec is not racy
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#408 fix: CVE-2022-41723
  go.mod
  go.sum
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved
