Repository kubernetes/kube-openapi, pull requests merged in 2023-02, with the labels that each got.

#345 Create smarter cache, and use them in handlers (v2 and v3)
  pkg/cached/cache.go
  pkg/cached/cache_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#372 Fix json unmarshal bug with extensions and Responses
  pkg/spec3/response.go
  pkg/spec3/response_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#374 Update go-json-experiment to latest version
  .github/workflows/ci.yml
  hack/JSON-EXPERIMENTAL-HASH
  hack/update-json-library.sh
  pkg/internal/third_party/go-json-experiment/README.md
  pkg/internal/third_party/go-json-experiment/json/arshal.go
  pkg/internal/third_party/go-json-experiment/json/arshal_any.go
  pkg/internal/third_party/go-json-experiment/json/arshal_default.go
  pkg/internal/third_party/go-json-experiment/json/arshal_inlined.go
  pkg/internal/third_party/go-json-experiment/json/arshal_methods.go
  pkg/internal/third_party/go-json-experiment/json/arshal_test.go
  pkg/internal/third_party/go-json-experiment/json/arshal_time.go
  pkg/internal/third_party/go-json-experiment/json/decode.go
  pkg/internal/third_party/go-json-experiment/json/decode_test.go
  pkg/internal/third_party/go-json-experiment/json/encode.go
  pkg/internal/third_party/go-json-experiment/json/fuzz_test.go
  pkg/internal/third_party/go-json-experiment/json/pools.go
  pkg/internal/third_party/go-json-experiment/json/state.go
  pkg/internal/third_party/go-json-experiment/json/token.go
  pkg/internal/third_party/go-json-experiment/json/value.go
  pkg/internal/third_party/go-json-experiment/json/value_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#369 Replaced Mime subtype containing @ with . in mimePb
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/handler3/handler.go
  pkg/handler3/handler_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved, tide/merge-method-squash, ok-to-test

#325 Use "jsonv2"/go-json-experimental to marshal OpenAPI v2
  go.mod
  go.sum
  pkg/aggregator/aggregator_test.go
  pkg/builder/openapi_test.go
  pkg/builder3/openapi_test.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
  pkg/internal/flags.go
  pkg/internal/serialization.go
  pkg/openapiconv/convert_test.go
  pkg/schemamutation/walker_test.go
  pkg/spec3/component_test.go
  pkg/spec3/operation_test.go
  pkg/util/jsontesting/json_roundtrip.go
  pkg/validation/spec/gnostic_test.go
  pkg/validation/spec/header.go
  pkg/validation/spec/info.go
  pkg/validation/spec/items.go
  pkg/validation/spec/operation.go
  pkg/validation/spec/parameter.go
  pkg/validation/spec/path_item.go
  pkg/validation/spec/paths.go
  pkg/validation/spec/response.go
  pkg/validation/spec/responses.go
  pkg/validation/spec/schema.go
  pkg/validation/spec/security_scheme.go
  pkg/validation/spec/swagger.go
  pkg/validation/spec/swagger_test.go
  pkg/validation/spec/tag.go
  test/integration/go.sum
  test/integration/testdata/golden.v2.json
Labels: cncf-cla: yes, lgtm, size/XL, approved

#370 Add fuzzer for OpenAPI V3
  pkg/spec3/benchmark_serialization_test.go
  pkg/spec3/fuzz.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#368 Experimental unmarshal for OpenAPI V3
  pkg/internal/flags.go
  pkg/spec3/benchmark_serialization_test.go
  pkg/spec3/encoding.go
  pkg/spec3/encoding_test.go
  pkg/spec3/example.go
  pkg/spec3/example_test.go
  pkg/spec3/external_documentation.go
  pkg/spec3/external_documentation_test.go
  pkg/spec3/header.go
  pkg/spec3/header_test.go
  pkg/spec3/media_type.go
  pkg/spec3/media_type_test.go
  pkg/spec3/operation.go
  pkg/spec3/operation_test.go
  pkg/spec3/parameter.go
  pkg/spec3/parameter_test.go
  pkg/spec3/path.go
  pkg/spec3/path_test.go
  pkg/spec3/request_body.go
  pkg/spec3/request_body_test.go
  pkg/spec3/response.go
  pkg/spec3/response_test.go
  pkg/spec3/security_scheme_test.go
  pkg/spec3/server.go
  pkg/spec3/server_test.go
  pkg/spec3/spec.go
Labels: cncf-cla: yes, lgtm, size/XL, approved
