Repository kubernetes/kube-openapi, pull requests merged in 2024-02, with the labels that each got.

#447 feature: make cel marker comments aware of reason and field path
  pkg/generators/markers.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#453 test/integration: bump timeout to 20s
  test/integration/integration_suite_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#452 refactor: make CommentTags internal
  pkg/generators/markers.go
  pkg/generators/markers_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#448 feature: add explicit +required
  pkg/generators/openapi.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#454 bugfix: emit enum in schema when used as list or map element
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#455 bugfix: dont throw error if +required is set with omitempty
  pkg/generators/enum.go
  pkg/generators/enum_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  pkg/generators/union.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#458 Use gengo/v2 in kube-openapi
  cmd/openapi-gen/args/args.go
  cmd/openapi-gen/openapi-gen.go
  go.mod
  go.sum
  pkg/generators/api_linter.go
  pkg/generators/config.go
  pkg/generators/enum.go
  pkg/generators/enum_test.go
  pkg/generators/extension.go
  pkg/generators/extension_test.go
  pkg/generators/markers.go
  pkg/generators/markers_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  pkg/generators/rules/idl_tag.go
  pkg/generators/rules/idl_tag_test.go
  pkg/generators/rules/names_match.go
  pkg/generators/rules/names_match_test.go
  pkg/generators/rules/omitempty_match_case.go
  pkg/generators/rules/omitempty_match_case_test.go
  pkg/generators/union.go
  test/integration/go.mod
  test/integration/go.sum
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#459 Fix feedback from previous PR
  cmd/openapi-gen/args/args.go
  pkg/generators/config.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/integration_suite_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#460 bugfix: resolve non-determinism in deduplicating enum comments
  pkg/generators/enum.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#462 Drop go.mod version to 1.20
  go.mod
  go.sum
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/M, approved
