Repository kubernetes/kube-openapi, pull requests merged in 2024-04, with the labels that each got.

#467 .*: add verify script for go directive changes
  .github/workflows/ci.yml
  hack/verify-go-directive.sh
Labels: cncf-cla: yes, lgtm, size/M, approved

#465 bugfix: change log level from error to info
  pkg/generators/openapi.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#471 fix: use Go-syntax representation to generate description
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#472 Bump github.com/onsi/ginkgo/v2 to 2.17.2
  go.mod
  go.sum
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved

#473 Bump github.com/onsi/gomega to v1.33.1
  go.mod
  go.sum
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved
