Repository kubernetes/kube-openapi, pull requests merged in 2024-05, with the labels that each got.

#475 Bump github.com/NYTimes/gziphandler to v1.1.1
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved

#464 bump go-restful to v3.11 to match k/k
  go.mod
  go.sum
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved

#469 Allow marker comments to extend validations for subschemas
  pkg/generators/markers.go
  pkg/generators/markers_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved
