Repository kubernetes/kube-openapi, pull requests merged in 2024-01, with the labels that each got.

#435 Feature: Added support for OpenAPI validations marker comments
  go.mod
  go.sum
  pkg/generators/markers.go
  pkg/generators/markers_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/go.mod
  test/integration/go.sum
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v2.report
  test/integration/testdata/golden.v3.json
  test/integration/testdata/valuevalidation/alpha.go
  test/integration/testutil/testutil.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, tide/merge-method-squash, ok-to-test

#441 Use better API for string comparison
  pkg/generators/rules/names_match.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#442 Fix integration test route builder for go-restful > 3.8
  test/integration/testutil/testutil.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#440 Update README.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#444 removed error-join shim after go version update
  pkg/generators/markers.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#445 Adds support for CEL marker comments
  pkg/generators/markers.go
  pkg/generators/markers_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/pkg/generated/openapi_generated.go
  test/integration/testdata/golden.v2.json
  test/integration/testdata/golden.v3.json
  test/integration/testdata/valuevalidation/alpha.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#446 add raw string/multiline syntax to marker comments
  pkg/generators/markers.go
  pkg/generators/markers_test.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved
