Repository kubernetes/kube-openapi, pull requests merged in 2025-06, with the labels that each got.

#384 Add k8s name related formats
  pkg/validation/strfmt/default_test.go
  pkg/validation/strfmt/format.go
  pkg/validation/strfmt/kubernetes-extensions.go
  pkg/validation/strfmt/kubernetes-extensions_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved

#545 Drop go 1.21 from supported versions
  .github/workflows/ci.yml
  go.mod
  test/integration/go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#542 Fix Method Return Types in OpenAPIDefinitionGetter and OpenAPIV3DefinitionGetter Interfaces
  pkg/builder/openapi_test.go
  pkg/builder3/openapi_test.go
  pkg/common/common.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#544 Bump gnostic-models and switch to using go.yaml.in/yaml/v3
  go.mod
  go.sum
  pkg/util/proto/document_v3.go
  pkg/validation/spec/gnostic_test.go
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/S, approved
