Repository kubernetes/kube-openapi, pull requests merged in 2025-03, with the labels that each got.

#524 Switch from gofuzz to randfill
  go.mod
  go.sum
  pkg/schemamutation/walker_test.go
  pkg/spec3/benchmark_serialization_test.go
  pkg/spec3/fuzz.go
  pkg/validation/spec/fuzz_test.go
  pkg/validation/spec/gnostic_test.go
  pkg/validation/spec/swagger_test.go
  test/integration/go.mod
  test/integration/go.sum
Labels: cncf-cla: yes, lgtm, size/XL, approved

#527 Increase integration tests' timeout to 1min
  test/integration/integration_suite_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#529 Fix idl package test naming
  pkg/idl/listtype_test.go
  pkg/idl/maptype_test.go
  pkg/idl/structtype_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#530 Add test for go 1.24
  .github/workflows/ci.yml
  pkg/idl/listtype_test.go
  pkg/idl/maptype_test.go
  pkg/idl/structtype_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#531 Add validation rules for streaming
  pkg/generators/api_linter.go
  pkg/generators/rules/list_type_streaming_tags.go
  pkg/generators/rules/list_type_streaming_tags_test.go
Labels: cncf-cla: yes, lgtm, size/L, approved
