Repository kubernetes/kube-openapi, pull requests merged in 2025-09, with the labels that each got.

#561 build: remove go 1.22 from testing matrix
  .github/workflows/ci.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#537 Add OpenAPIModelNamer and opt-in generator support
  cmd/openapi-gen/args/args.go
  pkg/generators/config.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  pkg/util/util.go
  test/integration/integration_suite_test.go
  test/integration/pkg/generated/namedmodels/openapi_generated.go
  test/integration/testdata/namedmodels/golden.v3.json
  test/integration/testdata/namedmodels/struct.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, sig/api-machinery, lifecycle/stale, triage/accepted

#562 Fix integration test
  test/integration/pkg/generated/namedmodels/openapi_generated.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#564 Compatiblity fix: Always use OpenAPIModelName() functions if they are avalable
  pkg/generators/config.go
  pkg/generators/openapi.go
  pkg/generators/openapi_test.go
  test/integration/naming_test.go
  test/integration/pkg/generated/namedmodels/openapi_generated.go
  test/integration/testdata/namedmodels/doc.go
  test/integration/testdata/namedmodels/struct.go
  test/integration/testdata/namedmodels/zz_generated_model_name.go
Labels: cncf-cla: yes, lgtm, size/L, approved
